CREATE SCHEMA IF NOT EXISTS app;

CREATE TABLE app.friendships (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    updated_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    receiver_id BIGINT NOT NULL,
    requester_id BIGINT NOT NULL,
    responded_at TIMESTAMP(6) WITH TIME ZONE,
    user_min_id BIGINT NOT NULL,
    user_max_id BIGINT NOT NULL,

    CONSTRAINT friendships_status_check
        CHECK (
            status IN ('PENDING', 'ACCEPTED', 'REJECTED')
        ),

    CONSTRAINT friendships_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_friendship_pair
        UNIQUE (requester_id, receiver_id)
);

CREATE TABLE app.movies (
    id BIGINT NOT NULL,
    overview TEXT,
    poster_path VARCHAR(500),
    rating DOUBLE PRECISION,
    release_date DATE,
    title VARCHAR(255) NOT NULL,

    CONSTRAINT movies_pkey
        PRIMARY KEY (id)
);

CREATE TABLE app.shares (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    message VARCHAR(500),
    movie_id BIGINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    recipient_id BIGINT NOT NULL,
    sender_id BIGINT NOT NULL,

    CONSTRAINT shares_status_check
        CHECK (
            status IN ('PENDING', 'ACCEPTED', 'REJECTED')
        ),

    CONSTRAINT shares_pkey
        PRIMARY KEY (id)
);

CREATE TABLE app.users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    nick VARCHAR(30) NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    avatar_icon VARCHAR(30),
    favorite_movie_id BIGINT,
    locked_until TIMESTAMP(6) WITH TIME ZONE,
    tokens_valid_after TIMESTAMP(6) WITH TIME ZONE,
    failed_login_attempts INTEGER DEFAULT 0 NOT NULL,

    CONSTRAINT users_avatar_icon_check
        CHECK (
            avatar_icon IN (
                'POPCORN',
                'CLAPPERBOARD',
                'FILM_REEL',
                'TICKET',
                'DIRECTOR_CHAIR',
                'STAR',
                'COMEDY_MASK',
                'TRAGEDY_MASK',
                'GHOST',
                'ROBOT',
                'ALIEN',
                'ASTRONAUT'
            )
        ),

    CONSTRAINT users_pkey
        PRIMARY KEY (id),

    CONSTRAINT ukfv31j6ho2093pmw8tgk7h8wtw
        UNIQUE (nick)
);

CREATE TABLE app.watchlist (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    created_at TIMESTAMP(6) WITH TIME ZONE NOT NULL,
    status VARCHAR(20) NOT NULL,
    movie_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,

    CONSTRAINT watchlist_status_check
        CHECK (
            status IN ('TO_WATCH', 'WATCHED')
        ),

    CONSTRAINT watchlist_pkey
        PRIMARY KEY (id),

    CONSTRAINT uk_watchlist_user_movie
        UNIQUE (user_id, movie_id)
);

ALTER TABLE app.shares
    ADD CONSTRAINT fk741d8s793fppq261sh1kj7fp5
    FOREIGN KEY (sender_id)
    REFERENCES app.users(id);

ALTER TABLE app.users
    ADD CONSTRAINT fk_user_favorite_movie
    FOREIGN KEY (favorite_movie_id)
    REFERENCES app.movies(id);

ALTER TABLE app.watchlist
    ADD CONSTRAINT fk_watchlist_movie
    FOREIGN KEY (movie_id)
    REFERENCES app.movies(id);

ALTER TABLE app.watchlist
    ADD CONSTRAINT fk_watchlist_user
    FOREIGN KEY (user_id)
    REFERENCES app.users(id);

ALTER TABLE app.friendships
    ADD CONSTRAINT fkas6bp8so5n3pfcqtfxt72e1ii
    FOREIGN KEY (requester_id)
    REFERENCES app.users(id);

ALTER TABLE app.shares
    ADD CONSTRAINT fkic1yspvbhayruux8b452h0agj
    FOREIGN KEY (recipient_id)
    REFERENCES app.users(id);

ALTER TABLE app.friendships
    ADD CONSTRAINT fkpk7w2cj6m9n224ny2t7fhi47
    FOREIGN KEY (receiver_id)
    REFERENCES app.users(id);

CREATE INDEX idx_share_recipient
    ON app.shares (recipient_id);

CREATE INDEX idx_share_sender
    ON app.shares (sender_id);

CREATE INDEX idx_share_status
    ON app.shares (status);

CREATE INDEX ix_friendship_receiver_status
    ON app.friendships (receiver_id, status);

CREATE INDEX ix_friendship_requester_status
    ON app.friendships (requester_id, status);